# Generated by Django 3.1.5 on 2021-03-13 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_mainarticle_icons'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='published',
            field=models.BooleanField(default=0),
        ),
    ]
