# Generated by Django 3.1.5 on 2021-04-02 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_article_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_title', models.CharField(max_length=200)),
                ('support_email', models.CharField(max_length=100)),
                ('company_logo', models.ImageField(upload_to='uploads/company_logo')),
                ('user_image', models.ImageField(upload_to='uploads/user_image')),
                ('about_me', models.CharField(max_length=500)),
                ('facebook_link', models.CharField(max_length=100)),
                ('twitter_link', models.CharField(max_length=100)),
                ('insta_link', models.CharField(max_length=100)),
                ('font', models.IntegerField(max_length=1)),
                ('header_color', models.IntegerField(max_length=1)),
                ('rtl_mode', models.BooleanField()),
                ('navigation_links', models.CharField(max_length=100)),
                ('navigation_links_title', models.CharField(max_length=100)),
                ('home_page', models.IntegerField(max_length=1)),
                ('layout_page', models.IntegerField(max_length=1)),
                ('article_page', models.IntegerField(max_length=1)),
                ('custom_domain', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(upload_to='uploads/article'),
        ),
    ]
