# Generated by Django 3.1.5 on 2021-04-02 18:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0008_auto_20210402_2311'),
    ]

    operations = [
        migrations.AddField(
            model_name='customization',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='customize', to='auth.user'),
            preserve_default=False,
        ),
    ]
